"""initial migration

Revision ID: 36699612f8c2
Revises: 
Create Date: 2019-12-17 15:35:58.449029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36699612f8c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('avatar', sa.String(length=200), nullable=True),
    sa.Column('tokens', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.Column('day', sa.String(length=15), nullable=False),
    sa.Column('campus', sa.String(length=50), nullable=True),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('level', sa.String(length=15), nullable=False),
    sa.Column('placement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['placement_id'], ['placements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('campus', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=15), nullable=True),
    sa.Column('year', sa.String(length=20), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    op.drop_table('groups')
    op.drop_table('users')
    op.drop_table('placements')
    # ### end Alembic commands ###
